name: Deploy Pages
# Copyright (c) 2022-2025 Asymmetric Effort LLC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v2
        with:
          branch: ${{ github.ref_name == 'main' && 'gh-pages' || format('gh-pages-{0}', github.ref_name) }}
          commit-message: Deploy ${{ github.ref }}
          cname: ${{ github.ref_name == 'main' && 'asymmetric-effort.com' || format('{0}.asymmetric-effort.com', github.ref_name) }}
